config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/admin/ng" => 'admin/ng', via: :post

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    
    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

    resources :images, :categories
    resources :users, only: [:show, :edit, :update]
  
    resources :images do
      member do
        put 'like', to: "images#vote"
      end
    end
  
    resources :users do
      resources :categories
    end

    resources :friendships, only: [:create, :destroy, :delete]
 
    resources :users
    resources :images do
      resources :comments
    end

    get "upload" => "images#new", :as => "upload"
    get 'contact-me', to: 'messages#new', as: 'new_message'
    post 'contact-me', to: 'messages#create', as: 'create_message'

    root to: "categories#index"

  end
end

app/models/user.rb
class User < ApplicationRecord
  include OmniauthAttributesConcern

  extend FriendlyId
  friendly_id :slug_add, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github google_oauth2 facebook]

  acts_as_voter

  has_many :user_authentications, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :images, through: :categories
  has_many :comments, dependent: :destroy

  has_many :active_friendships, class_name: "Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_friendships, class_name: "Friendship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower

  validates :username, presence:true
  validates :email, presence:true, uniqueness: true

  mount_uploader :avatar, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.slug = auth.info.name
      user.username = auth.info.name
      user.save!(validate: false)
    end
  end

  def slug_add
    [
      :username,
      [:username, rand(1..10)],
      [:username, rand(1..100)],
      [:username, rand(1..1000)]
    ]
  end

  def should_generate_new_friendly_id?
    username_changed?
  end

  def follow(user)
    active_friendships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
   following.include?(user)
  end

  def find_followers
    users_following = User.find followers.ids if followers.ids.any?
    begin
      MyMailer.some_changes_in_follow(users_following).deliver_now if users_following != nil
    rescue
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "GoogleOauth2") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    if verify_recaptcha
      super 
      begin
        MyMailer.welcome_email(current_user).deliver_now
      rescue
        # render html: "<script>alert('Could not send email!')</script>".html_safe
      end
    else
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    if verify_recaptcha
      super 
    else
      redirect_to new_user_session_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_friendly_user, except: [:update, :index]

  def show
    @user = User.friendly.find(params[:id])
    @u = User.find(@user.following.ids)
  end

  def edit
  end
  
  def update
    if current_user.update(user_params)
      redirect_to current_user
    else
      flash.now[:alert] = 'Please try again'
      render :edit
    end
  end
  
  private

    def set_friendly_user
      @user = User.friendly.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :avatar, :remove_avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show_pics.html.haml
- user.categories.each do |categories|
  - categories.images.each do |image|
    .box.panel.panel-default
      .panel.panel-default
        .panel-heading
          = image.image_title
        .panel-body
          = link_to image_tag(image.image_url(:thumb)), image_path(image), class:'rounded'
        .panel-footer
          = t('category.cat')
          = link_to "#{image.category.name}", category_path(image.category)
          %br
          - if image.category != nil
            = "#{t('submitted_by')}"
            = link_to "#{image.category.user.username}", user_path(image.category.user)

app/views/users/edit.html.haml
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    .h1 
      = t('edit')
      = t('profile')
    = form_for @user, html: { multipart: true } do |f|
      .form-group
        = f.label :username
        = f.text_field :username, class:'form-control'
      .form-group  
        = f.label :avatar
        = f.file_field :avatar, class:'form-control'
      %p
        %label
          = f.check_box :remove_avatar
          = t('user.remove_avatar')
      .form-group
        = f.label :first_name
        = f.text_field :first_name, class:'form-control'
      .form-group
        = f.label :last_name
        = f.text_field :last_name, class:'form-control'
      .form-group
        = f.label 'birthday'
        = f.date_field :birthday, class:'form-control'
      .actions
        = f.submit t('save'), class:'btn btn-light'

app/views/users/show.html.haml
.row
  .col-lg-2.col-md-3.col-xs-12
    .panel.panel-default
      #user.panel.panel-heading
        %h3
          = @user.username
      .panel.panel-body
        = image_tag @user.avatar.url(:profile), class:'rounded'# if @user.avatar?
        %br
        = @user.first_name
        = @user.last_name
      .panel.panel-footer
        = @user.email
        %br
        - if current_user == @user
          = link_to t('edit'), edit_user_path(@user)
        %br
        %br
        - if user_signed_in? && current_user != @user
          - if current_user.following?(@user)
            = button_to t('user.unfollow'), friendship_path(user_id:@user.id), method: :delete, class:'btn btn-light'
          - else
            = button_to t('user.follow'), friendships_path(user_id:@user.id), class:'btn btn-light'
        %br
          - if @user.following.any?
            - @u.each do |user|
              - user.categories.each do |category|
                = t("pics_category")
                = link_to "#{category.name}", category_path(id:category.id)
                %br
                = t("user_profile")
                = link_to "#{user.username}", user_path(id:user.id)
                %br
                %br
  .col-lg-5.col-md-5.col-xs-12
    %h5
      = t('user.my_pics')
    #pictures.transitions-enabled
      = render(partial: 'show_pics', locals: { user: @user})
  .col-lg-5.col-md-4.col-xs-12
    %h5
      = t("user.foll_pics")
    - if @user.following.any?
      - @u.each do |user|
        #pictures.transitions-enabled
          = render(partial: 'show_pics', locals: { user: user})