config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/admin/ng" => 'admin/ng', via: :post

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    
    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

    resources :images, :categories
    resources :users, only: [:show, :edit, :update]
  
    resources :images do
      member do
        put 'like', to: "images#vote"
      end
    end
  
    resources :users do
      resources :categories
    end

    resources :friendships, only: [:create, :destroy, :delete]
 
    resources :users
    resources :images do
      resources :comments
    end

    get "upload" => "images#new", :as => "upload"
    get 'contact-me', to: 'messages#new', as: 'new_message'
    post 'contact-me', to: 'messages#create', as: 'create_message'

    root to: "categories#index"

  end
end

app/views/shared/_edit_categories.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    - @category.errors.full_messages.each do |msg|
      .alert.alert-danger= msg
  .form-group
    = f.label t('category.new.name')
    = f.text_field :name, class:'form-control'

  = f.submit t('submit'), class:"button btn btn-light btn-default"
  = link_to t('cancel'), categories_path, class:'btn btn-light btn-default'

app/views/shared/_show_pics.html.haml
#pictures.transitions-enabled.pagination-centered.infinite-scroll.clearfix
  - if @images.exists?
    - @images.each do |image|
      .box.panel.panel-default
        .panel-heading
          = link_to image.image_title, image_path(image)
        .panel-body
          = link_to image_path(image) do
            = image_tag image.image_url(:thumb), class:'img-fluid rounded'
        .panel-footer
          = t('category.new.name')
          = link_to "#{image.category.name}", category_path(image.category)
          %br
          - if image.category != nil
            = t('submitted_by')
            = link_to image.category.user.username, user_path(image.category.user)