config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/admin/ng" => 'admin/ng', via: :post

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    
    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

    resources :images, :categories
    resources :users, only: [:show, :edit, :update]
  
    resources :images do
      member do
        put 'like', to: "images#vote"
      end
    end
  
    resources :users do
      resources :categories
    end

    resources :friendships, only: [:create, :destroy, :delete]
 
    resources :users
    resources :images do
      resources :comments
    end

    get "upload" => "images#new", :as => "upload"
    get 'contact-me', to: 'messages#new', as: 'new_message'
    post 'contact-me', to: 'messages#create', as: 'create_message'

    root to: "categories#index"

  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }

  def top_image
    images.order(:cached_votes_up => :desc).first
  end

  def find_followers(user)
    u = User.find_by id: user.followers.ids if user.followers.ids.any?
    MyMailer.with(user: u).some_changes_in_follow(u).deliver_now
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_category, only: [:show, :edit, :update, :destroy] 
  before_action :all_categories, only: [:index, :show, :edit]

  def index
  end

  def show
    @images = @category.images.order(created_at: :asc).page(params[:page]).per(25)
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    
    if @category.save
      @image = @category.images.build
      flash[:success] = t('categories.create.flash.success')
      render 'images/new'
    else
      render 'new'
    end
  end

  def edit
    @images = @category.images
    render 'edit'
  end

  def update
    if @category.update(category_params)
      current_user.find_followers
      flash[:success] = t('categories.update.flash.success')
      redirect_to category_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    if @category.user.email == current_user.email
      @category.destroy
      flash[:notice] = t('categories.destroy.flash.notice')
    else
      flash[:alert] = t('categories.destroy.flash.error')
    end

    redirect_to images_path
  end

  private

    def all_categories
      @categories = Category.all
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def find_category
      @category = Category.find(params[:id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.haml
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    %h2 
      = t('category.edit')
    = render 'shared/edit_categories'

#editor
  %h3
    Images in #{@category.name}
#pictures.transitions-enabled
  - if @category.images.exists?
    - @category.images.each do |image|
      .box.panel.panel-default
        .panel.panel-default
          .panel-heading
            = image_tag image.image_url(:thumb)
            = link_to t('delete'), image_path(image), class:'delete', method: :delete, data: {confirm: 'Are you sure?'}

app/views/categories/index.html.haml
#pictures.transitions-enabled
  - if @categories.exists?
    - @categories.each do |category|
      .box.panel.panel-default 
        .panel-heading
          = link_to category.name, category_path(category) #(user_id:@user.id)
        .panel-body
          - if category.images.exists?
            = link_to category.top_image.image_title, category_path(category)
            = link_to category_path(category) do
              = image_tag category.top_image.image_url(:thumb), class:'rounded'
        .panel-footer
          submitted by
          = link_to category.user.username, user_path(category.user)

app/views/categories/new.html.haml
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    %h1 
      = I18n.t('category.new.title')

    = render 'shared/edit_categories'

app/views/categories/show.html.haml
#editor
  %h1
    = @category.name
  - if current_user == @category.user
    = link_to t('category.edit'), edit_category_path, class:'btn btn-light'
    = link_to t('category.delete'), category_path, class:'delete btn btn-light', method: :delete, data: {confirm: t('ar_sure')}
    = link_to t('category.add_image'), upload_path, class:'btn btn-light'
= render 'shared/show_pics'
.container-fluid
  = paginate @images