config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/admin/ng" => 'admin/ng', via: :post

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    
    devise_for :users, skip: :omniauth_callbacks, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

    resources :images, :categories
    resources :users, only: [:show, :edit, :update]
  
    resources :images do
      member do
        put 'like', to: "images#vote"
      end
    end
  
    resources :users do
      resources :categories
    end

    resources :friendships, only: [:create, :destroy, :delete]
 
    resources :users
    resources :images do
      resources :comments
    end

    get "upload" => "images#new", :as => "upload"
    get 'contact-me', to: 'messages#new', as: 'new_message'
    post 'contact-me', to: 'messages#create', as: 'create_message'

    root to: "categories#index"

  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  before_save :update_image_attributes

  validates_processing_of :image
  validates_presence_of :image
  validate :image_size_validatio
  
  acts_as_votable

  private
    def update_image_attributes
      if image.present?
        self.image_file_size = image.file.size	
      end
    end

    def image_size_validatio
      errors[:image] << "should be less than 1500KB" if image.size > 1.5.megabytes
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, only: [:create, :destroy, :show, :vote]
  after_action :mail_to_user, only: [:create, :update, :destroy]
  respond_to :js, :json, :html

  def index
    @images = Image.order(created_at: :desc).page(params[:page]).per(35)
    @categories = Category.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)
    
    if @image.save
      flash[:success] = t('images.create.flash.success')
      redirect_back(fallback_location: root_path)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @image.update(image_params)
      flash[:success] = t('images.update.flash.success')
    else
      flash[:alert] = t('image.update.flash.error')
    end
    redirect_to image_path
  end
 
  def destroy
    if @image.category.user.id == current_user.id
      @image.destroy
      flash[:notice] = t('images.update.flash.notice')
    else
      flash[:alert] = t('image.destroy.flash.error')
    end
    redirect_to root_path
  end

  def vote
    record_activity('Likes a picture')
    
    if !current_user.liked? @image
      @image.liked_by current_user
    else 
      if current_user.liked? @image
        @image.unliked_by current_user
      end
    end
  end

  private
    def image_params
      params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type, :remote_image_url)
    end

    def find_image
      @image = Image.find(params[:id])
    end

    def mail_to_user
      current_user.find_followers
    end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.haml
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    %h1 
      = t('image.edit_image_description')
    - if @image.errors.any?
      - @image.errors.full_messages.each do |msg|
        .alert.alert-danger= msg
    = form_for @image, :html => {:multipart => true} do |f|
      = image_tag @image.image_url(:thumb), class:'img-fluid rounded'
      %br
      .form-group
        = f.label t('image.im')
        = f.file_field :image, class:'form-control'
      .form-group
        = f.label :image_title
        = f.text_area :image_title, class:'form-control'
      .form-group
        = f.label :image_description
        = f.text_area :image_description, class:'form-control'
      .form-group
        = f.submit t('submit'), class:'btn btn-light'
        = link_to t('cancel'), image_path, class:'btn btn-light'

app/views/images/index.html.haml
= render 'shared/show_pics'
%nav#page-nav
  = link_to_next_page @images, ''

app/views/images/new.html.haml
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    %h1 
      = t('image.upload_image')
    = form_for @image, :html => {:multipart => true} do |f|
      - if @image.errors.any?
        - @image.errors.full_messages.each do |msg|
          .alert.alert-danger 
            = msg
      .form-group
        = f.label :image_title
        = f.text_field :image_title, class:'form-control'
      .form-group
        = f.label t('category.new.name')
        = f.select :category_id, current_user.categories.collect {|x| [x.name, x.id]}, { include_blank: t('categories.select')}, class:'form-control'
      .form-group
        = f.label :image_description
        = f.text_area :image_description, class:'form-control'
      .form-group
        = f.label :image
        = f.file_field :image
      = f.submit t('submit'), class:'btn btn-light'
      = link_to t('cancel'), images_path, class:'btn btn-light'

app/views/images/show.html.haml
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    .row
      .col-12
        %h1= @image.image_title
    .row
      .col-12
        .panel-show
          .picture-show
            = image_tag @image.image_url(:large), class:'img-fluid rounded'
    .row
      .col-lg-3.col-md-3.col-xs-2
        .picture-show
          = link_to like_image_path(@image), class: "like-btn", method: :put, remote: :true do
            %span
              %i.fa.fa-heart
            %span.likes-count= @image.get_upvotes.size
      .col-lg-5.col-md-5.col-xs-4
        .picture-show
          = t('submitted_by')
          - if user_signed_in?
            = link_to @image.category.user.username, user_path(@image.category.user.id)
          - else
            = @image.category.user.username
      .col-lg-4.col-md-4.col-md-6
        .picture-show
          - if @image.category.user == current_user
            = link_to t('edit'), edit_image_path, class: "btn btn-default"
            = link_to t('delete'), image_path(@image), method: :delete, data: { confirm: t("ar_sure") }, class: "btn btn-default"
    .row
      .col-12
        = @image.image_description
%br
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    = link_to t('back'), images_path, class: "btn btn-default"
%br
.row
  .col-lg-8.offset-lg-2.col-md-10.offset-md-1.col-xs-12
    %h4
      = t('comment.add')
    = render 'comments/form'
    = render @image.comments

app/views/images/vote.js.erb
<% if current_user.liked? @image %>
  $('.like-btn').addClass('liked');
<% else %>
  $('.like-btn').removeClass('like-btn');
<% end %>
$('.likes-count').html("<%= @image.get_upvotes.size %>")